doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Shipping:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Shipping/Application'
                prefix: 'Shipping\Application'
                alias: Shipping
            Sales:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Sales/Application'
                prefix: 'Sales\Application'
                alias: Sales
