doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
#            TunnelAchat:
#                is_bundle: false
#                type: attribute
#                dir: '%kernel.project_dir%/src/TunnelAchat/Domain/Model'
#                prefix: 'TunnelAchat\Domain\Model'
#                alias: TunnelAchat
